### ISSUE TITLE
Can CircSplice be used for usual RNA sequencing data not rRNA or linear RNA depleted?

### ISSUE THREAD

**Issue by tjhwangxiong** [GeneFeng/CircSplice#1]
Dear Prof. Jing Feng

As suggested in the readme file, libraries with rRNA depleted and treated by RNase R were suggested for circRNA and circ-AS detection. We hope to know whether usual RNA sequencing data not rRNA or linear RNA depleted could be applied using CircSplice?

Thanks.

**Comment by GeneFeng** [comment]
Sequencing of total RNA with rRNA and linear RNA depleted can enrich the circRNAs. However, total RNA without those treatment can also be used for the identification of circRNA.
